=== riceconfetti/daily-drip/.astro/collections/characters.schema.json
{
  "$ref": "#/definitions/characters",
  "definitions": {
    "characters": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        },
        "element": {
          "type": "string"
        },
        "weaponType": {
          "type": "string"
        },
        "bannerName": {
          "type": "string"
        },
        "colors": {
          "type": "object",
          "properties": {
            "primary": {
              "type": "string"
            },
            "secondary": {
              "type": "string"
            },
            "textAccent": {
              "type": "string"
            }
          },
          "required": [
            "primary",
            "secondary",
            "textAccent"
          ],
          "additionalProperties": false
        },
        "images": {
          "type": "object",
          "properties": {
            "gachaSplash": {
              "type": "string"
            },
            "gachaCard": {
              "type": "string"
            },
            "bannerCard": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "rarity",
        "element"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== riceconfetti/daily-drip/src/content/characters/wuwa/chixia.json
{
  "name": "Chixia",
  "rarity": 4,
  "element": "fusion",
  "weaponType": "pistols",
  "images": {
    "gachaSplash": "./images/characters/wuwa/chixia/gachaSpash.png",
    "gachaCard": "./images/characters/wuwa/chixia/gachaCard.png",
    "bannerCard": "./images/characters/wuwa/chixia/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/wuwa/xiangliyao.json
{
	"name": "Xiangli Yao",
	"rarity": 5,
	"element": "electro",
	"weaponType": "gauntlets",
	"bannerName": "Celestial Revelation",
	"colors": {
		"primary": "bg-gradient-to-r from-[#181D51] to-[#87C0EF]",
		"secondary": "bg-gradient-to-t from-[#3C4475] to-[#6A7B8900]",
		"textAccent": "text-[#617EAF]"
	}
}

=== riceconfetti/daily-drip/src/content/characters/genshin/mona.json
{
	"name": "Mona",
	"rarity": 5,
	"element": "hydro",
	"bannerName": "",
	"images": {
		"gachaSplash": "mona/gachaSplash",
		"gachaCard": "mona/gachaCard",
		"bannerCard": "mona/bannerCard"
	},
	"colors": {
		"primary": "bg-gradient-to-r from-[#422A71] to-[#A1AAE9]",
		"secondary": "bg-gradient-to-t from-[#492E7F] to-[#8453E500]",
		"textAccent": "text-[#EBB38F]"
	}
}

=== riceconfetti/daily-drip/src/content/characters/genshin/nilou.json
{
  "name": "Nilou",
  "rarity": 5,
  "element": "hydro",
  "weaponType": "sword",
  "bannerName": "Twirling Lotus",
  "colors": {
    "primary": "bg-gradient-to-r from-[#002E54] to-[#EA8E71]",
    "secondary": "bg-gradient-to-t from-[#972218] to-[#9DCADD00]",
    "textAccent": "text-[#F25D43]"
  },
  "images": {
    "gachaSplash": "./images/characters/genshin/nilou/gachaSpash.png",
    "gachaCard": "./images/characters/genshin/nilou/gachaCard.png",
    "bannerCard": "./images/characters/genshin/nilou/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/starrail/lingsha.json
{"name":"Lingsha","rarity":5,"element":"fire","weaponType":"abundance","bannerName":"???","colors":{"primary":"bg-gradient-to-r from-[#392916] to-[#D88F45]","secondary":"bg-gradient-to-t from-[#392916] to-[#8F541700]","textAccent":"text-[#D88F45]"},"images":{"gachaSplash":"lingsha/gachaSpash","gachaCard":"lingsha/gachaCard","bannerCard":"lingsha/bannerCard"}}

=== riceconfetti/daily-drip/src/content/characters/wuwa/calcharo.json
{
  "name": "Calcharo",
  "rarity": 5,
  "element": "electro",
  "weaponType": "broadblade",
  "bannerName": "?????",
  "images": {
    "gachaSplash": "./assets/characters/wuwa/calcharo/gachaSpash.png",
    "gachaCard": "./assets/characters/wuwa/calcharo/gachaCard.png",
    "bannerCard": "./assets/characters/wuwa/calcharo/bannerCard.png"
  },
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  }
}

=== riceconfetti/daily-drip/src/content/characters/starrail/natasha.json
{
  "name": "Natasha",
  "rarity": 4,
  "element": "physical",
  "images": {
    "gachaSplash": "./images/characters/starrail/natasha/gachaSpash.png",
    "gachaCard": "./images/characters/starrail/natasha/gachaCard.png",
    "bannerCard": "./images/characters/starrail/natasha/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/nahida.json
{
  "name": "Nahida",
  "rarity": 5,
  "element": "dendro",
  "bannerName": "The Moongrass' Enlightenment",
  "images": {
    "gachaSplash": "./assets/characters/genshin/nahida/gachaSpash.png",
    "gachaCard": "./assets/characters/genshin/nahida/gachaCard.png",
    "bannerCard": "./assets/characters/genshin/nahida/bannerCard.png"
  },
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  }
}
