=== riceconfetti/daily-drip/.astro/collections/characters.schema.json
{
  "$ref": "#/definitions/characters",
  "definitions": {
    "characters": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        },
        "element": {
          "type": "string"
        },
        "weaponType": {
          "type": "string"
        },
        "bannerName": {
          "type": "string"
        },
        "colors": {
          "type": "object",
          "properties": {
            "primary": {
              "type": "string"
            },
            "secondary": {
              "type": "string"
            },
            "textAccent": {
              "type": "string"
            }
          },
          "required": [
            "primary",
            "secondary",
            "textAccent"
          ],
          "additionalProperties": false
        },
        "images": {
          "type": "object",
          "properties": {
            "gachaSplash": {
              "type": "string"
            },
            "gachaCard": {
              "type": "string"
            },
            "bannerCard": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "rarity",
        "element"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== riceconfetti/daily-drip/src/content/characters/wuwa/jinhsi.json
{
  "name": "Jinhsi",
  "rarity": 5,
  "element": "spectro",
  "weaponType": "broadblade",
  "bannerName": "?????",
  "images": {
    "gachaSplash": "./assets/characters/wuwa/jinhsi/gachaSpash.png",
    "gachaCard": "./assets/characters/wuwa/jinhsi/gachaCard.png",
    "bannerCard": "./assets/characters/wuwa/jinhsi/bannerCard.png"
  },
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  }
}

=== riceconfetti/daily-drip/src/content/characters/starrail/kafka.json
{
  "name": "Kafka",
  "rarity": 5,
  "element": "lightning",
  "weaponType": "nihility",
  "bannerName": "Nessun Dorma",
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  },
  "images": {
    "gachaSplash": "./images/characters/kafaka/gachaSpash.png",
    "gachaCard": "./images/characters/kafaka/gachaCard.png",
    "bannerCard": "./images/characters/kafaka/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/kaeya.json
{
  "name": "Kaeya",
  "rarity": 4,
  "element": "cryo",
  "weaponType": "sword",
  "images": {
    "gachaSplash": "./assets/characters/genshin/kaeya/gachaSpash.png",
    "gachaCard": "./assets/characters/genshin/kaeya/gachaCard.png",
    "bannerCard": "./assets/characters/genshin/kaeya/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/starrail/feixiao.json
{
  "name": "Feixiao",
  "rarity": 5,
  "element": "starrail",
  "weaponType": "starrail",
  "bannerName": "???",
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  },
  "images": {
    "gachaSplash": "./images/characters/feixiao/gachaSpash.png",
    "gachaCard": "./images/characters/feixiao/gachaCard.png",
    "bannerCard": "./images/characters/feixiao/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/kamisatoayato.json
{
	"name": "Kamisato Ayato",
	"rarity": 5,
	"element": "hydro",
	"weaponType": "sword",
	"bannerName": "Azure Excursion",
	"images": {
		"gachaSplash": "kamisatoayato/gachaSplash",
		"gachaCard": "kamisatoayato/gachaCard",
		"bannerCard": "kamisatoayato/bannerCard"
	},
	"colors": {
		"primary": "bg-gradient-to-r from-[#233B64] to-[#4876AA]",
		"secondary": "bg-gradient-to-t from-[#1E1A4D] to-[#69B8EF00]",
		"textAccent": "text-[#BCCEEC]"
	}
}

=== riceconfetti/daily-drip/src/content/characters/starrail/bronya.json
{
  "name": "Bronya",
  "rarity": 5,
  "element": "wind",
  "weaponType": "harmony",
  "bannerName": "",
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  },
  "images": {
    "gachaSplash": "/assets/characters/starrail/bronya/gachaSpash",
    "gachaCard": "/assets/characters/starrail/bronya/gachaCard",
    "bannerCard": "/assets/characters/starrail/bronya/bannerCard"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/xilonen.json
{
	"name": "Xilonen",
	"rarity": 5,
	"element": "geo",
	"weaponType": "Sword",
	"bannerName": "?????",
	"images": {
		"gachaSplash": "xilonen/gachaSplash",
		"gachaCard": "xilonen/gachaCard",
		"bannerCard": "xilonen/bannerCard"
	},
	"colors": {
		"primary": "bg-gradient-to-r from-[#000] to-[#fff]",
		"secondary": "bg-gradient-to-t from-[#000] to-[#fff00]",
		"textAccent": "text-[#fff]"
	}
}

=== riceconfetti/daily-drip/src/content/characters/starrail/aventurine.json
{
  "name": "Aventurine",
  "rarity": 5,
  "element": "imaginary",
  "weaponType": "preservation",
  "bannerName": "Gilded Imprisonment",
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  },
  "images": {
    "gachaSplash": "/assets/characters/starrail/aventurine/gachaSpash",
    "gachaCard": "/assets/characters/starrail/aventurine/gachaCard",
    "bannerCard": "/assets/characters/starrail/aventurine/bannerCard"
  }
}
