=== riceconfetti/daily-drip/.astro/collections/characters.schema.json
{
  "$ref": "#/definitions/characters",
  "definitions": {
    "characters": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        },
        "element": {
          "type": "string"
        },
        "weaponType": {
          "type": "string"
        },
        "bannerName": {
          "type": "string"
        },
        "colors": {
          "type": "object",
          "properties": {
            "primary": {
              "type": "string"
            },
            "secondary": {
              "type": "string"
            },
            "textAccent": {
              "type": "string"
            }
          },
          "required": [
            "primary",
            "secondary",
            "textAccent"
          ],
          "additionalProperties": false
        },
        "images": {
          "type": "object",
          "properties": {
            "gachaSplash": {
              "type": "string"
            },
            "gachaCard": {
              "type": "string"
            },
            "bannerCard": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "rarity",
        "element"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== riceconfetti/daily-drip/src/content/characters/starrail/misha.json
{
  "name": "Misha",
  "rarity": 4,
  "element": "ice",
  "weaponType": "destruction",
  "images": {
    "gachaSplash": "/assets/characters/starrail/misha/gachaSpash",
    "gachaCard": "/assets/characters/starrail/misha/gachaCard",
    "bannerCard": "/assets/characters/starrail/misha/bannerCard"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/ningguang.json
{
  "name": "Ningguang",
  "rarity": 4,
  "element": "geo",
  "images": {
    "gachaSplash": "./assets/characters/genshin/ningguang/gachaSpash.png",
    "gachaCard": "./assets/characters/genshin/ningguang/gachaCard.png",
    "bannerCard": "./assets/characters/genshin/ningguang/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/mualani.json
{
	"name": "Mualani",
	"rarity": 5,
	"element": "hydro",
	"weaponType": "Catalyst",
	"bannerName": "Sharktacular Safari",
	"images": {
		"gachaSplash": "mualani/gachaSplash",
		"gachaCard": "mualani/gachaCard",
		"bannerCard": "mualani/bannerCard"
	},
	"colors": {
		"primary": "bg-gradient-to-r from-[#142677] to-[#25D8FD]",
		"secondary": "bg-gradient-to-t from-[#02407D] to-[#0078D400]",
		"textAccent": "text-[#F7C91E]"
	}
}

=== riceconfetti/daily-drip/src/content/characters/starrail/acheron.json
{
	"name": "Acheron",
	"rarity": 5,
	"element": "lightning",
	"weaponType": "nihility",
	"bannerName": "Words of Yore",
	"images": {
		"gachaSplash": "acheron/gachaSpash",
		"gachaCard": "acheron/gachaCard",
		"bannerCard": "acheron/bannerCard"
	},
	"colors": {
		"primary": "bg-gradient-to-r from-[#222357] to-[#D9D5FC]",
		"secondary": "bg-gradient-to-t from-[#121337] to-[#D9D5FC00]",
		"textAccent": "text-[#F33241]"
	}
}

=== riceconfetti/daily-drip/src/content/characters/starrail/hanya.json
{
  "name": "Hanya",
  "rarity": 4,
  "element": "physical",
  "weaponType": "harmony",
  "images": {
    "gachaSplash": "/assets/characters/starrail/hanya/gachaSpash",
    "gachaCard": "/assets/characters/starrail/hanya/gachaCard",
    "bannerCard": "/assets/characters/starrail/hanya/bannerCard"
  }
}

=== riceconfetti/daily-drip/src/content/characters/starrail/yanqing.json
{
  "name": "Yanqing",
  "rarity": 5,
  "element": "ice",
  "weaponType": "hunt",
  "bannerName": "",
  "images": {
    "gachaSplash": "/assets/characters/starrail/yanqing/gachaSpash",
    "gachaCard": "/assets/characters/starrail/yanqing/gachaCard",
    "bannerCard": "/assets/characters/starrail/yanqing/bannerCard"
  },
  "colors": {
    "primary": "bg-gradient-to-r from-[#000] to-[#fff]",
    "secondary": "bg-gradient-to-t from-[#000] to-[#ffffff00]",
    "textAccent": "text-[#999]"
  }
}

=== riceconfetti/daily-drip/src/content/characters/starrail/lynx.json
{
  "name": "Lynx",
  "rarity": 4,
  "element": "quantum",
  "weaponType": "abundance",
  "images": {
    "gachaSplash": "./images/characters/starrail/lynx/gachaSpash.png",
    "gachaCard": "./images/characters/starrail/lynx/gachaCard.png",
    "bannerCard": "./images/characters/starrail/lynx/bannerCard.png"
  }
}

=== riceconfetti/daily-drip/src/content/characters/genshin/chasca.json
{
	"name": "Chasca",
	"rarity": 5,
	"images": {
		"gachaSplash": "chasca/gachaSplash",
		"gachaCard": "chasca/gachaCard",
		"bannerCard": "chasca/bannerCard"
	},
	"element": "genshin",
	"weaponType": "genshin",
	"bannerName": "?????",
	"colors": {
		"primary": "bg-gradient-to-r from-[#000] to-[#FFF]",
		"secondary": "bg-gradient-to-t from-[#000] to-[#FFF00]",
		"textAccent": "text-[#000]"
	}
}
